-- create USER_AUTHENTICATE table
CREATE TABLE USER_AUTHENTICATE (
ID int NOT NULL AUTO_INCREMENT ,
USER_NAME VARCHAR(255),
PASSWORD VARCHAR(255),
TOKEN VARCHAR(255),
primary key (id)
);

-- INSERT USER AUTHENTICATE DATA
INSERT INTO USER_AUTHENTICATE (USER_NAME, PASSWORD, TOKEN) VALUES ('+84586099640', '123456', '12313DSDASDSD');
