package com.dropship.uploadshoppeart.request;

public class CreateArtShopeeRq {
  public static String tuiDeoNuRequest ="{\n" + "    \"product_info\": {\n" + "        \"name\": \"$ARTICLE_NAME\",\n"
      + "        \"enable_model_level_dts\": false,\n" + "        \"category_path\": [\n" + "            100016,\n"
      + "            100092\n" + "        ],\n" + "        \"weight\": {\n" + "            \"unit\": 2,\n"
      + "            \"value\": \"800\"\n" + "        },\n" + "        \"condition\": 1,\n"
      + "        \"parent_sku\": \"\",\n" + "        \"brand_id\": 0,\n" + "        \"attributes\": [],\n"
      + "        \"images\": [\n" + "            \"vn-11134207-7r98o-lnwhfeu90pkqd7\"\n" + "        ],\n"
      + "        \"long_images\": [],\n" + "        \"tier_variation\": [\n" + "            {\n"
      + "                \"name\": \"\",\n" + "                \"options\": [\n" + "                    \"\"\n"
      + "                ],\n" + "                \"images\": []\n" + "            }\n" + "        ],\n"
      + "        \"size_chart_info\": {\n" + "            \"size_chart_id\": 0,\n"
      + "            \"size_chart\": \"\"\n" + "        },\n" + "        \"video_list\": [],\n"
      + "        \"description_info\": {\n" + "            \"description\": \"$ARTICLE_DESCRIPTION\",\n"
      + "            \"description_type\": \"normal\"\n" + "        },\n" + "        \"dimension\": {\n"
      + "            \"width\": \"\",\n" + "            \"height\": \"\",\n" + "            \"length\": \"\"\n"
      + "        },\n" + "        \"pre_order_info\": {\n" + "            \"pre_order\": false,\n"
      + "            \"days_to_ship\": 2\n" + "        },\n" + "        \"wholesale_list\": [],\n"
      + "        \"category_recommend_info\": {\n"
      + "            \"category_recommend_id\": \"d2a0543a-95a2-4d14-8c08-580f58e3a735\",\n"
      + "            \"is_prefilled\": false,\n" + "            \"selected_category_path\": [\n"
      + "                100016,\n" + "                100092\n" + "            ]\n" + "        },\n"
      + "        \"ds_attr_rcmd_id\": \"d2a0543a-95a2-4d14-8c08-580f58e3a735\",\n" + "        \"unlisted\": true,\n"
      + "        \"logistics_channels\": [\n" + "            {\n" + "                \"size\": 0,\n"
      + "                \"price\": \"18300\",\n" + "                \"cover_shipping_fee\": false,\n"
      + "                \"enabled\": true,\n" + "                \"channelid\": 5001,\n"
      + "                \"sizeid\": 0\n" + "            },\n" + "            {\n" + "                \"size\": 0,\n"
      + "                \"price\": \"14850\",\n" + "                \"cover_shipping_fee\": false,\n"
      + "                \"enabled\": true,\n" + "                \"channelid\": 5002,\n"
      + "                \"sizeid\": 0\n" + "            }\n" + "        ],\n" + "        \"model_list\": [\n"
      + "            {\n" + "                \"id\": 0,\n" + "                \"tier_index\": [\n"
      + "                    0\n" + "                ],\n" + "                \"is_default\": true,\n"
      + "                \"price\": \"1000000\",\n" + "                \"stock_setting_list\": [\n"
      + "                    {\n" + "                        \"sellable_stock\": 2\n" + "                    }\n"
      + "                ]\n" + "            }\n" + "        ]\n" + "    },\n" + "    \"is_draft\": false\n" + "}&{\n"
      + "    \"route_pattern\": \"/^\\\\/portal\\\\/product\\\\/list\\\\/all(?:\\\\/(?=$))?$/i\",\n"
      + "    \"nav_type\": 2,\n" + "    \"region\": \"vn\",\n" + "    \"is_cn\": false\n" + "}&{\n"
      + "    \"tags\": [\n" + "        \"web-performance\"\n" + "    ],\n" + "    \"view\": \"ALL\",\n"
      + "    \"sdk_name\": \"mdap_web_sdk\",\n" + "    \"sdk_version\": \"0.4.19\",\n"
      + "    \"os_name\": \"Windows\",\n" + "    \"os_version\": \"10\",\n"
      + "    \"device_id\": \"814b720d5a362c7f55d58ec213a6ae5d\",\n" + "    \"switch_config_labels\": {\n"
      + "        \"app_version\": \"1.0.1\"\n" + "    },\n"
      + "    \"sdk_spec_checksum\": \"f414bd59a57264c82aed4854159049ae806d7d02ab2bb2759475293caccb0bbf\",\n"
      + "    \"switch_config_keys\": [\n" + "        {\n" + "            \"key\": \"switch_config\",\n"
      + "            \"checksum\": \"-1\",\n" + "            \"sample_sub_key\": \"app_sample\",\n"
      + "            \"default_sample_rate\": 0.1,\n" + "            \"is_sampled\": true\n" + "        }\n"
      + "    ],\n" + "    \"algorithm_version\": \"v1\"\n" + "}&{\n" + "    \"version\": \"1.0.1\"\n" + "}&{\n"
      + "    \"item_id_list\": [\n" + "        22669873527\n" + "    ]\n" + "}&{\n"
      + "    \"page_hash\": -1342353436,\n" + "    \"tti\": 433,\n" + "    \"site\": \"VN\"\n" + "}&{\n"
      + "    \"event_timestamp\": 1699594665791,\n" + "    \"app_name\": \"seller-center-product-list\",\n"
      + "    \"app_version\": \"1.0.1\",\n" + "    \"app_build_id\": \"1.0.1\",\n" + "    \"user_id\": \"\",\n"
      + "    \"sdk_name\": \"mdap_web_sdk\",\n" + "    \"sdk_version\": \"0.4.19\",\n"
      + "    \"session_id\": \"b938c925-bdd6-428f-95b9-0ded4beb1f56\",\n" + "    \"tag\": \"web-performance\",\n"
      + "    \"os_name\": \"Windows\",\n" + "    \"os_version\": \"10\",\n"
      + "    \"device_id\": \"814b720d5a362c7f55d58ec213a6ae5d\",\n" + "    \"labels\": {\n"
      + "        \"supportFetch\": \"true\",\n" + "        \"supportFetchKeepAlive\": \"true\",\n"
      + "        \"supportSendBeacon\": \"true\",\n" + "        \"supportLocalstorage\": \"true\",\n"
      + "        \"supportObserveType\": \"true\",\n" + "        \"supportGetEntriesByType\": \"true\"\n" + "    },\n"
      + "    \"data\": {\n"
      + "        \"browser\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36\",\n"
      + "        \"browser_name\": \"Chrome\",\n" + "        \"browser_version\": \"119.0.0.0\",\n"
      + "        \"engine_name\": \"Blink\",\n" + "        \"engine_version\": \"119.0.0.0\",\n"
      + "        \"screen_dpr\": 1.25,\n" + "        \"screen_height\": 864,\n" + "        \"screen_width\": 1536,\n"
      + "        \"connection_type\": \"3g\",\n" + "        \"connection_downlink\": 1382.4,\n"
      + "        \"connection_rtt\": 300,\n" + "        \"region\": \"vn\",\n" + "        \"environment\": \"live\",\n"
      + "        \"entries\": [\n" + "            {\n" + "                \"type\": \"customized\",\n"
      + "                \"customized_point_id\": \"1517084e13350409356118788163cbad\",\n"
      + "                \"duration\": 28,\n" + "                \"customized_data\": {\n"
      + "                    \"environment\": \"live\",\n" + "                    \"mainland\": \"local\"\n"
      + "                }\n" + "            },\n" + "            {\n" + "                \"type\": \"customized\",\n"
      + "                \"customized_point_id\": \"035e67910a782690c19ec199f9e630ef\",\n"
      + "                \"duration\": 20,\n" + "                \"customized_data\": {\n"
      + "                    \"environment\": \"live\",\n" + "                    \"mainland\": \"local\"\n"
      + "                }\n" + "            },\n" + "            {\n"
      + "                \"start_timestamp\": 1699594663800,\n" + "                \"end_timestamp\": 1699594663847,\n"
      + "                \"url\": \"https://banhang.shopee.vn/api/v3/mpsku/list/get_component_visible_info\",\n"
      + "                \"page_url\": \"https://banhang.shopee.vn/portal/product/list/all\",\n"
      + "                \"duration\": 47,\n" + "                \"http_method\": \"GET\",\n"
      + "                \"http_status_code\": 200,\n" + "                \"logic_status_code\": 0,\n"
      + "                \"type\": \"api\"\n" + "            },\n" + "            {\n"
      + "                \"start_timestamp\": 1699594663801,\n" + "                \"end_timestamp\": 1699594663848,\n"
      + "                \"url\": \"https://banhang.shopee.vn/api/v3/mpsku/list/get_component_disabled_info\",\n"
      + "                \"page_url\": \"https://banhang.shopee.vn/portal/product/list/all\",\n"
      + "                \"duration\": 47,\n" + "                \"http_method\": \"GET\",\n"
      + "                \"http_status_code\": 200,\n" + "                \"logic_status_code\": 0,\n"
      + "                \"type\": \"api\"\n" + "            },\n" + "            {\n"
      + "                \"start_timestamp\": 1699594663802,\n" + "                \"end_timestamp\": 1699594663856,\n"
      + "                \"url\": \"https://banhang.shopee.vn/api/v3/mpsku/list/get_component_blocking_info\",\n"
      + "                \"page_url\": \"https://banhang.shopee.vn/portal/product/list/all\",\n"
      + "                \"duration\": 54,\n" + "                \"http_method\": \"GET\",\n"
      + "                \"http_status_code\": 200,\n" + "                \"logic_status_code\": 0,\n"
      + "                \"type\": \"api\"\n" + "            },\n" + "            {\n"
      + "                \"start_timestamp\": 1699594663802,\n" + "                \"end_timestamp\": 1699594663857,\n"
      + "                \"url\": \"https://banhang.shopee.vn/api/v3/mpsku/list/get_banner_info\",\n"
      + "                \"page_url\": \"https://banhang.shopee.vn/portal/product/list/all\",\n"
      + "                \"duration\": 55,\n" + "                \"http_method\": \"GET\",\n"
      + "                \"http_status_code\": 200,\n" + "                \"logic_status_code\": 0,\n"
      + "                \"type\": \"api\"\n" + "            },\n" + "            {\n"
      + "                \"start_timestamp\": 1699594663805,\n" + "                \"end_timestamp\": 1699594663861,\n"
      + "                \"url\": \"https://banhang.shopee.vn/api/v3/mpsku/list/get_entry_blocking_info\",\n"
      + "                \"page_url\": \"https://banhang.shopee.vn/portal/product/list/all\",\n"
      + "                \"duration\": 56,\n" + "                \"http_method\": \"GET\",\n"
      + "                \"http_status_code\": 200,\n" + "                \"logic_status_code\": 0,\n"
      + "                \"type\": \"api\"\n" + "            },\n" + "            {\n"
      + "                \"start_timestamp\": 1699594663876,\n" + "                \"end_timestamp\": 1699594663922,\n"
      + "                \"url\": \"https://banhang.shopee.vn/api/v3/mpsku/list/get_bumped_product_list\",\n"
      + "                \"page_url\": \"https://banhang.shopee.vn/portal/product/list/all\",\n"
      + "                \"duration\": 46,\n" + "                \"http_method\": \"GET\",\n"
      + "                \"http_status_code\": 200,\n" + "                \"logic_status_code\": 0,\n"
      + "                \"type\": \"api\"\n" + "            },\n" + "            {\n"
      + "                \"start_timestamp\": 1699594663879,\n" + "                \"end_timestamp\": 1699594663925,\n"
      + "                \"url\": \"https://banhang.shopee.vn/api/tool/mass_product/get_category_tree/\",\n"
      + "                \"page_url\": \"https://banhang.shopee.vn/portal/product/list/all\",\n"
      + "                \"duration\": 46,\n" + "                \"http_method\": \"POST\",\n"
      + "                \"http_status_code\": 200,\n" + "                \"logic_status_code\": 0,\n"
      + "                \"type\": \"api\"\n" + "            },\n" + "            {\n"
      + "                \"start_timestamp\": 1699594663881,\n" + "                \"end_timestamp\": 1699594663932,\n"
      + "                \"url\": \"https://banhang.shopee.vn/api/v3/product/get_product_constraints/\",\n"
      + "                \"page_url\": \"https://banhang.shopee.vn/portal/product/list/all\",\n"
      + "                \"duration\": 51,\n" + "                \"http_method\": \"GET\",\n"
      + "                \"http_status_code\": 200,\n" + "                \"logic_status_code\": 0,\n"
      + "                \"type\": \"api\"\n" + "            },\n" + "            {\n"
      + "                \"start_timestamp\": 1699594663880,\n" + "                \"end_timestamp\": 1699594663934,\n"
      + "                \"url\": \"https://banhang.shopee.vn/api/v3/product/get_shop_warehouse/\",\n"
      + "                \"page_url\": \"https://banhang.shopee.vn/portal/product/list/all\",\n"
      + "                \"duration\": 54,\n" + "                \"http_method\": \"GET\",\n"
      + "                \"http_status_code\": 200,\n" + "                \"logic_status_code\": 0,\n"
      + "                \"type\": \"api\"\n" + "            },\n" + "            {\n"
      + "                \"start_timestamp\": 1699594663884,\n" + "                \"end_timestamp\": 1699594663935,\n"
      + "                \"url\": \"https://banhang.shopee.vn/api/v3/size_chart/get_converted_size_chart_list_with_paging\",\n"
      + "                \"page_url\": \"https://banhang.shopee.vn/portal/product/list/all\",\n"
      + "                \"duration\": 51,\n" + "                \"http_method\": \"GET\",\n"
      + "                \"http_status_code\": 200,\n" + "                \"logic_status_code\": 0,\n"
      + "                \"type\": \"api\"\n" + "            },\n" + "            {\n"
      + "                \"start_timestamp\": 1699594663878,\n" + "                \"end_timestamp\": 1699594663943,\n"
      + "                \"url\": \"https://banhang.shopee.vn/api/v3/mpsku/list/get_product_list\",\n"
      + "                \"page_url\": \"https://banhang.shopee.vn/portal/product/list/all\",\n"
      + "                \"duration\": 65,\n" + "                \"http_method\": \"GET\",\n"
      + "                \"http_status_code\": 200,\n" + "                \"logic_status_code\": 0,\n"
      + "                \"type\": \"api\"\n" + "            },\n" + "            {\n"
      + "                \"type\": \"customized\",\n"
      + "                \"customized_point_id\": \"bf2f3f09a44ac7fd8712c1577554c1ad\",\n"
      + "                \"duration\": 61,\n" + "                \"customized_data\": {\n"
      + "                    \"environment\": \"live\",\n" + "                    \"mainland\": \"local\",\n"
      + "                    \"pageName\": \"mpsku-list\",\n" + "                    \"skuType\": \"LOCAL\"\n"
      + "                }\n" + "            },\n" + "            {\n" + "                \"type\": \"customized\",\n"
      + "                \"customized_point_id\": \"8e0ed28757b81a294368952eab062abb\",\n"
      + "                \"duration\": 72,\n" + "                \"customized_data\": {\n"
      + "                    \"environment\": \"live\",\n" + "                    \"mainland\": \"local\",\n"
      + "                    \"pageName\": \"mpsku-list\",\n" + "                    \"skuType\": \"LOCAL\"\n"
      + "                }\n" + "            },\n" + "            {\n" + "                \"type\": \"customized\",\n"
      + "                \"customized_point_id\": \"0009cdb879d8dd248f6ef113fd4e125c\",\n"
      + "                \"duration\": 211,\n" + "                \"customized_data\": {\n"
      + "                    \"environment\": \"live\",\n" + "                    \"mainland\": \"local\",\n"
      + "                    \"pageName\": \"mpsku-list\",\n" + "                    \"skuType\": \"LOCAL\"\n"
      + "                }\n" + "            },\n" + "            {\n" + "                \"type\": \"customized\",\n"
      + "                \"customized_point_id\": \"d310828fbfcd4468d32908cc4764ba75\",\n"
      + "                \"duration\": 396,\n" + "                \"customized_data\": {\n"
      + "                    \"environment\": \"live\",\n" + "                    \"mainland\": \"local\",\n"
      + "                    \"pageName\": \"mpsku-list\",\n" + "                    \"skuType\": \"LOCAL\"\n"
      + "                }\n" + "            },\n" + "            {\n" + "                \"type\": \"customized\",\n"
      + "                \"customized_point_id\": \"ed5771c7fe9bec0a9ef49928c802f97f\",\n"
      + "                \"duration\": 401,\n" + "                \"customized_data\": {\n"
      + "                    \"environment\": \"live\",\n" + "                    \"mainland\": \"local\",\n"
      + "                    \"pageName\": \"mpsku-list\",\n" + "                    \"skuType\": \"LOCAL\"\n"
      + "                }\n" + "            },\n" + "            {\n" + "                \"type\": \"customized\",\n"
      + "                \"customized_point_id\": \"70a970e9ae556d227f97ef1927e4ed80\",\n"
      + "                \"duration\": 429,\n" + "                \"customized_data\": {\n"
      + "                    \"environment\": \"live\",\n" + "                    \"mainland\": \"local\",\n"
      + "                    \"pageName\": \"mpsku-list\",\n" + "                    \"skuType\": \"LOCAL\"\n"
      + "                }\n" + "            },\n" + "            {\n"
      + "                \"start_timestamp\": 1699594664087,\n" + "                \"end_timestamp\": 1699594664077,\n"
      + "                \"url\": \"https://banhang.shopee.vn/api/v3/product/get_campaign_info_by_item_list/\",\n"
      + "                \"page_url\": \"https://banhang.shopee.vn/portal/product/list/all\",\n"
      + "                \"duration\": -10,\n" + "                \"http_method\": \"POST\",\n"
      + "                \"http_status_code\": 200,\n" + "                \"logic_status_code\": 0,\n"
      + "                \"type\": \"api\"\n" + "            }\n" + "        ],\n" + "        \"api_performances\": [\n"
      + "            {\n"
      + "                \"url\": \"https://banhang.shopee.vn/api/v3/mpsku/list/get_component_visible_info\",\n"
      + "                \"page_url\": \"https://banhang.shopee.vn/portal/product/list/all\",\n"
      + "                \"start_time\": 520928,\n" + "                \"duration\": 78,\n"
      + "                \"connect_start\": 520928,\n" + "                \"connect_end\": 520928,\n"
      + "                \"domain_lookup_start\": 520928,\n" + "                \"domain_lookup_end\": 520928,\n"
      + "                \"redirect_start\": 0,\n" + "                \"redirect_end\": 0,\n"
      + "                \"request_start\": 520929,\n" + "                \"response_start\": 521003,\n"
      + "                \"response_end\": 521005,\n" + "                \"worker_start\": 0,\n"
      + "                \"fetch_start\": 520928,\n" + "                \"secure_connection_start\": 520928\n"
      + "            },\n" + "            {\n"
      + "                \"url\": \"https://banhang.shopee.vn/api/v3/mpsku/list/get_component_disabled_info\",\n"
      + "                \"page_url\": \"https://banhang.shopee.vn/portal/product/list/all\",\n"
      + "                \"start_time\": 520928,\n" + "                \"duration\": 69,\n"
      + "                \"connect_start\": 520928,\n" + "                \"connect_end\": 520928,\n"
      + "                \"domain_lookup_start\": 520928,\n" + "                \"domain_lookup_end\": 520928,\n"
      + "                \"redirect_start\": 0,\n" + "                \"redirect_end\": 0,\n"
      + "                \"request_start\": 520929,\n" + "                \"response_start\": 520995,\n"
      + "                \"response_end\": 520997,\n" + "                \"worker_start\": 0,\n"
      + "                \"fetch_start\": 520928,\n" + "                \"secure_connection_start\": 520928\n"
      + "            },\n" + "            {\n"
      + "                \"url\": \"https://banhang.shopee.vn/api/v3/mpsku/list/get_component_blocking_info\",\n"
      + "                \"page_url\": \"https://banhang.shopee.vn/portal/product/list/all\",\n"
      + "                \"start_time\": 520929,\n" + "                \"duration\": 68,\n"
      + "                \"connect_start\": 520929,\n" + "                \"connect_end\": 520929,\n"
      + "                \"domain_lookup_start\": 520929,\n" + "                \"domain_lookup_end\": 520929,\n"
      + "                \"redirect_start\": 0,\n" + "                \"redirect_end\": 0,\n"
      + "                \"request_start\": 520930,\n" + "                \"response_start\": 520995,\n"
      + "                \"response_end\": 520997,\n" + "                \"worker_start\": 0,\n"
      + "                \"fetch_start\": 520929,\n" + "                \"secure_connection_start\": 520929\n"
      + "            },\n" + "            {\n"
      + "                \"url\": \"https://banhang.shopee.vn/api/v3/mpsku/list/get_banner_info\",\n"
      + "                \"page_url\": \"https://banhang.shopee.vn/portal/product/list/all\",\n"
      + "                \"start_time\": 520929,\n" + "                \"duration\": 72,\n"
      + "                \"connect_start\": 520929,\n" + "                \"connect_end\": 520929,\n"
      + "                \"domain_lookup_start\": 520929,\n" + "                \"domain_lookup_end\": 520929,\n"
      + "                \"redirect_start\": 0,\n" + "                \"redirect_end\": 0,\n"
      + "                \"request_start\": 520932,\n" + "                \"response_start\": 520996,\n"
      + "                \"response_end\": 521001,\n" + "                \"worker_start\": 0,\n"
      + "                \"fetch_start\": 520929,\n" + "                \"secure_connection_start\": 520929\n"
      + "            },\n" + "            {\n"
      + "                \"url\": \"https://banhang.shopee.vn/api/v3/mpsku/list/get_entry_blocking_info\",\n"
      + "                \"page_url\": \"https://banhang.shopee.vn/portal/product/list/all\",\n"
      + "                \"start_time\": 520933,\n" + "                \"duration\": 84,\n"
      + "                \"connect_start\": 520933,\n" + "                \"connect_end\": 520933,\n"
      + "                \"domain_lookup_start\": 520933,\n" + "                \"domain_lookup_end\": 520933,\n"
      + "                \"redirect_start\": 0,\n" + "                \"redirect_end\": 0,\n"
      + "                \"request_start\": 520934,\n" + "                \"response_start\": 521015,\n"
      + "                \"response_end\": 521016,\n" + "                \"worker_start\": 0,\n"
      + "                \"fetch_start\": 520933,\n" + "                \"secure_connection_start\": 520933\n"
      + "            },\n" + "            {\n"
      + "                \"url\": \"https://banhang.shopee.vn/api/v3/mpsku/list/get_bumped_product_list\",\n"
      + "                \"page_url\": \"https://banhang.shopee.vn/portal/product/list/all\",\n"
      + "                \"start_time\": 521004,\n" + "                \"duration\": 67,\n"
      + "                \"connect_start\": 521004,\n" + "                \"connect_end\": 521004,\n"
      + "                \"domain_lookup_start\": 521004,\n" + "                \"domain_lookup_end\": 521004,\n"
      + "                \"redirect_start\": 0,\n" + "                \"redirect_end\": 0,\n"
      + "                \"request_start\": 521007,\n" + "                \"response_start\": 521069,\n"
      + "                \"response_end\": 521071,\n" + "                \"worker_start\": 0,\n"
      + "                \"fetch_start\": 521004,\n" + "                \"secure_connection_start\": 521004\n"
      + "            },\n" + "            {\n"
      + "                \"url\": \"https://banhang.shopee.vn/api/v3/mpsku/list/get_product_list\",\n"
      + "                \"page_url\": \"https://banhang.shopee.vn/portal/product/list/all\",\n"
      + "                \"start_time\": 521006,\n" + "                \"duration\": 122,\n"
      + "                \"connect_start\": 521006,\n" + "                \"connect_end\": 521006,\n"
      + "                \"domain_lookup_start\": 521006,\n" + "                \"domain_lookup_end\": 521006,\n"
      + "                \"redirect_start\": 0,\n" + "                \"redirect_end\": 0,\n"
      + "                \"request_start\": 521007,\n" + "                \"response_start\": 521121,\n"
      + "                \"response_end\": 521127,\n" + "                \"worker_start\": 0,\n"
      + "                \"fetch_start\": 521006,\n" + "                \"secure_connection_start\": 521006\n"
      + "            },\n" + "            {\n"
      + "                \"url\": \"https://banhang.shopee.vn/api/tool/mass_product/get_category_tree/\",\n"
      + "                \"page_url\": \"https://banhang.shopee.vn/portal/product/list/all\",\n"
      + "                \"start_time\": 521007,\n" + "                \"duration\": 117,\n"
      + "                \"connect_start\": 521007,\n" + "                \"connect_end\": 521007,\n"
      + "                \"domain_lookup_start\": 521007,\n" + "                \"domain_lookup_end\": 521007,\n"
      + "                \"redirect_start\": 0,\n" + "                \"redirect_end\": 0,\n"
      + "                \"request_start\": 521008,\n" + "                \"response_start\": 521121,\n"
      + "                \"response_end\": 521123,\n" + "                \"worker_start\": 0,\n"
      + "                \"fetch_start\": 521007,\n" + "                \"secure_connection_start\": 521007\n"
      + "            },\n" + "            {\n"
      + "                \"url\": \"https://banhang.shopee.vn/api/v3/product/get_shop_warehouse/\",\n"
      + "                \"page_url\": \"https://banhang.shopee.vn/portal/product/list/all\",\n"
      + "                \"start_time\": 521008,\n" + "                \"duration\": 118,\n"
      + "                \"connect_start\": 521008,\n" + "                \"connect_end\": 521008,\n"
      + "                \"domain_lookup_start\": 521008,\n" + "                \"domain_lookup_end\": 521008,\n"
      + "                \"redirect_start\": 0,\n" + "                \"redirect_end\": 0,\n"
      + "                \"request_start\": 521011,\n" + "                \"response_start\": 521121,\n"
      + "                \"response_end\": 521125,\n" + "                \"worker_start\": 0,\n"
      + "                \"fetch_start\": 521008,\n" + "                \"secure_connection_start\": 521008\n"
      + "            },\n" + "            {\n"
      + "                \"url\": \"https://banhang.shopee.vn/api/v3/product/get_product_constraints/\",\n"
      + "                \"page_url\": \"https://banhang.shopee.vn/portal/product/list/all\",\n"
      + "                \"start_time\": 521008,\n" + "                \"duration\": 116,\n"
      + "                \"connect_start\": 521008,\n" + "                \"connect_end\": 521008,\n"
      + "                \"domain_lookup_start\": 521008,\n" + "                \"domain_lookup_end\": 521008,\n"
      + "                \"redirect_start\": 0,\n" + "                \"redirect_end\": 0,\n"
      + "                \"request_start\": 521012,\n" + "                \"response_start\": 521121,\n"
      + "                \"response_end\": 521124,\n" + "                \"worker_start\": 0,\n"
      + "                \"fetch_start\": 521008,\n" + "                \"secure_connection_start\": 521008\n"
      + "            },\n" + "            {\n"
      + "                \"url\": \"https://banhang.shopee.vn/api/v3/size_chart/get_converted_size_chart_list_with_paging\",\n"
      + "                \"page_url\": \"https://banhang.shopee.vn/portal/product/list/all\",\n"
      + "                \"start_time\": 521011,\n" + "                \"duration\": 114,\n"
      + "                \"connect_start\": 521011,\n" + "                \"connect_end\": 521011,\n"
      + "                \"domain_lookup_start\": 521011,\n" + "                \"domain_lookup_end\": 521011,\n"
      + "                \"redirect_start\": 0,\n" + "                \"redirect_end\": 0,\n"
      + "                \"request_start\": 521013,\n" + "                \"response_start\": 521121,\n"
      + "                \"response_end\": 521125,\n" + "                \"worker_start\": 0,\n"
      + "                \"fetch_start\": 521011,\n" + "                \"secure_connection_start\": 521011\n"
      + "            },\n" + "            {\n"
      + "                \"url\": \"https://banhang.shopee.vn/api/v3/product/get_campaign_info_by_item_list/\",\n"
      + "                \"page_url\": \"https://banhang.shopee.vn/portal/product/list/all\",\n"
      + "                \"start_time\": 521214,\n" + "                \"duration\": 85,\n"
      + "                \"connect_start\": 521214,\n" + "                \"connect_end\": 521214,\n"
      + "                \"domain_lookup_start\": 521214,\n" + "                \"domain_lookup_end\": 521214,\n"
      + "                \"redirect_start\": 0,\n" + "                \"redirect_end\": 0,\n"
      + "                \"request_start\": 521216,\n" + "                \"response_start\": 521298,\n"
      + "                \"response_end\": 521299,\n" + "                \"worker_start\": 0,\n"
      + "                \"fetch_start\": 521214,\n" + "                \"secure_connection_start\": 521214\n"
      + "            }\n" + "        ]\n" + "    }\n" + "}&{\n" + "    \"event_timestamp\": 1699594660943,\n"
      + "    \"app_name\": \"pc-common-custom-points\",\n" + "    \"app_version\": \"1.0.0\",\n"
      + "    \"app_build_id\": \"1.0.0\",\n" + "    \"user_id\": \"\",\n" + "    \"sdk_name\": \"mdap_web_sdk\",\n"
      + "    \"sdk_version\": \"0.4.19\",\n" + "    \"session_id\": \"b938c925-bdd6-428f-95b9-0ded4beb1f56\",\n"
      + "    \"tag\": \"web-custom\",\n" + "    \"os_name\": \"Windows\",\n" + "    \"os_version\": \"10\",\n"
      + "    \"device_id\": \"814b720d5a362c7f55d58ec213a6ae5d\",\n" + "    \"labels\": {\n"
      + "        \"supportFetch\": \"true\",\n" + "        \"supportFetchKeepAlive\": \"true\",\n"
      + "        \"supportSendBeacon\": \"true\",\n" + "        \"supportLocalstorage\": \"true\"\n" + "    },\n"
      + "    \"data\": {\n"
      + "        \"browser\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36\",\n"
      + "        \"browser_name\": \"Chrome\",\n" + "        \"browser_version\": \"119.0.0.0\",\n"
      + "        \"engine_name\": \"Blink\",\n" + "        \"engine_version\": \"119.0.0.0\",\n"
      + "        \"screen_dpr\": 1.25,\n" + "        \"screen_height\": 864,\n" + "        \"screen_width\": 1536,\n"
      + "        \"connection_type\": \"3g\",\n" + "        \"connection_downlink\": 1382.4,\n"
      + "        \"connection_rtt\": 300,\n" + "        \"region\": \"vn\",\n" + "        \"environment\": \"live\",\n"
      + "        \"custom_accums\": [\n" + "            {\n"
      + "                \"point_id\": \"547853d89bc08f35855ebc7ab66dc0a4\",\n"
      + "                \"timestamp\": 1699594657710,\n" + "                \"data\": {}\n" + "            },\n"
      + "            {\n" + "                \"point_id\": \"e7c7bb5c2eeee6bc2f50335cb018b9a5\",\n"
      + "                \"timestamp\": 1699594658692,\n" + "                \"data\": {}\n" + "            },\n"
      + "            {\n" + "                \"point_id\": \"5b7cffd004a435212a5eb0a0ad2d4642\",\n"
      + "                \"timestamp\": 1699594658952,\n" + "                \"data\": {}\n" + "            },\n"
      + "            {\n" + "                \"point_id\": \"f05d71c64c7fa38d7270538875a5fdf7\",\n"
      + "                \"timestamp\": 1699594658954,\n" + "                \"data\": {}\n" + "            },\n"
      + "            {\n" + "                \"point_id\": \"f5d51a2958052ff3de339c5f2563ecd8\",\n"
      + "                \"timestamp\": 1699594659162,\n" + "                \"data\": {}\n" + "            }\n"
      + "        ]\n" + "    }\n" + "}";

  public static void main(String[] args) {
    System.out.println(tuiDeoNuRequest);
  }
}
